#!/usr/bin/env python3
"""
Lecture 4 data: Lecture 5's multi-product shop, plus the flat sales file.

    python3 build_data.py        # writes into data/

Lecture 4 uses the same data as Lecture 5: an order can hold several
products. This script does not generate that data -- it COPIES it from
../lecture_5/data/ (built by ../lecture_5/generate_data.py; never
modified here) and adds the one file Lecture 4 needs that Lecture 5
doesn't have:

  customers.csv, employees.csv, products.csv,
  orders.csv, order_items.csv     copied unchanged from Lecture 5
  sales_flat.csv                  NEW: the flat file, one row per ORDER
                                  LINE (965 rows) with the order header,
                                  customer, employee and product written
                                  out on every line -- what the four
                                  tables would look like as one sheet
  all_inserts.sql                 Lecture 5's INSERT fallback, plus the
                                  sales rows (fallback for \\copy)

The flat file is used by the NATURAL JOIN trap, the name-join trap and
the lossless-split proof. Its rows follow orders.csv, then each order's
lines in order_items.csv order. Values are copied as text exactly as
they appear in the source CSVs, so the database reads the same numbers
from both shapes. Re-running reproduces the files byte for byte.
"""
import csv
import shutil
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / "../lecture_5/data"
OUT = HERE / "data"
OUT.mkdir(exist_ok=True)

TABLES = ["customers", "employees", "products", "orders", "order_items"]

def read(name):
    with open(SRC / f"{name}.csv", newline="") as f:
        return list(csv.DictReader(f))

# ---- 1. copy Lecture 5's five tables unchanged ------------------------------
for t in TABLES:
    shutil.copyfile(SRC / f"{t}.csv", OUT / f"{t}.csv")

# ---- 2. the flat file, one row per order line -------------------------------
customers = {r["customerID"]: r for r in read("customers")}
employees = {r["employeeID"]: r for r in read("employees")}
products = {r["productID"]: r for r in read("products")}
lines_by_order = {}
for r in read("order_items"):
    lines_by_order.setdefault(r["orderID"], []).append(r)

COLUMNS = [
    "orderID", "orderDate", "orderTime", "channel", "status", "paymentMethod",
    "deliveryDate", "rating", "orderTotal",
    "quantity", "unitPrice", "discountPct", "lineTotal",
    "customerFirstName", "customerLastName", "customerEmail", "customerCity",
    "customerBirthDate", "customerSignupDate", "customerAnniversary", "customerMoneySpent",
    "employeeFirstName", "employeeLastName", "employeePosition", "employeeBranch",
    "productName", "productCategory", "productBrand", "productPrice", "productCost",
]

rows = []
for o in read("orders"):
    c = customers[o["customerID"]]
    e = employees.get(o["employeeID"], {})          # online orders: no employee
    for line in lines_by_order[o["orderID"]]:
        p = products[line["productID"]]
        rows.append([
            o["orderID"], o["orderDate"], o["orderTime"], o["channel"], o["status"], o["paymentMethod"],
            o["deliveryDate"], o["rating"], o["orderTotal"],
            line["quantity"], line["unitPrice"], line["discountPct"], line["lineTotal"],
            c["firstName"], c["lastName"], c["email"], c["city"],
            c["birthDate"], c["signupDate"], c["anniversary"], c["moneySpent"],
            e.get("firstName", ""), e.get("lastName", ""), e.get("position", ""), e.get("branch", ""),
            p["productName"], p["category"], p["brand"], p["price"], p["cost"],
        ])

with open(OUT / "sales_flat.csv", "w", newline="") as f:
    w = csv.writer(f, lineterminator="\n")
    w.writerow(COLUMNS)
    w.writerows(rows)

# ---- 3. the INSERT fallback --------------------------------------------------
def sql_value(v):
    return "NULL" if v == "" else "'" + v.replace("'", "''") + "'"

l5 = (SRC / "all_inserts.sql").read_text().split("\n")
body = "\n".join(l for l in l5 if not l.startswith("--")).strip("\n")
with open(OUT / "all_inserts.sql", "w") as f:
    f.write("-- Lecture 4 data as INSERT statements: the fallback if \\copy doesn't work.\n")
    f.write("-- Generated by build_data.py -- edit that (or Lecture 5's generator), not this file.\n")
    f.write("-- Run after the CREATE TABLE part of steps/00-setup.sql.\n\n")
    f.write(body + "\n\n")
    f.write(f"INSERT INTO sales ({', '.join(COLUMNS)}) VALUES\n")
    f.write(",\n".join("  (" + ", ".join(sql_value(v) for v in r) + ")" for r in rows) + ";\n")

print(f"copied {len(TABLES)} tables; sales_flat.csv: {len(rows)} rows")
