-- ============================================================
-- Lecture 4 — Putting the Tables Back Together
-- YSU, Data Science for Business
--
-- Every statement of the lecture in one runnable file, each followed by
-- its result. Data models, the order_items junction table, JOIN in
-- detail (cross, inner, aliases, USING/NATURAL, left/right/full,
-- anti-join, WHERE vs ON, self, wrong key, fan-out, range joins,
-- GROUP BY), a star schema at line grain, and a verification drill.
--
-- Data: Lecture 5's shop -- an order can hold several products
-- (600 orders, 965 lines) -- plus the flat sales file, one row per line.
--
-- Run from the lecture_4/ folder so the \copy paths resolve:
--     psql postgres
--     \i lecture-04-demo.sql
-- Three statements error ON PURPOSE -- the comments say which.
-- Generated by build_demo.py from steps/ -- edit those, not this file.
-- ============================================================



-- ============================================================
-- Lecture 4 — Part 0: load the data
-- Creates the lecture04 database if missing, and connects to it.
-- ============================================================

-- ============================================================
-- Lecture 4 — Part 0: load the data
--
-- The shop from Lecture 3, with one change: an order can hold SEVERAL
-- products, the way a real shopping cart does. Creates SIX tables:
--
--   customers    \
--   employees     |  the people and the catalogue (employees gets a
--   products     /   managerID column: who each person reports to)
--   orders        one row per ORDER -- the header: who bought, when,
--                 where, status, and the order's total. No product
--                 columns: products live on the lines.
--   order_items   one row per PRODUCT IN AN ORDER -- the lines: which
--                 product, how many, at what price. Primary key
--                 (orderID, productID): a product appears once per order.
--   sales         the flat file: one row per order LINE, with the order,
--                 customer, employee and product written out on every
--                 row. The same facts as the five tables above, in one
--                 sheet.
--
-- The data is Lecture 5's (copied into data/ by build_data.py, which
-- also writes the flat file). 235 of the 600 orders have more than one
-- line; 965 lines in all.
--
-- Creates the lecture04 database too, if it doesn't exist yet, and
-- connects to it -- so you can start psql in ANY database.
-- \copy resolves paths relative to where you STARTED psql, so run this
-- from the lecture_4/ folder:     psql postgres
--                                 \i steps/00-setup.sql
-- Safe to re-run: drops and recreates every table.
-- ============================================================

-- ---- The database: create it only if it's missing ----
-- Postgres has no CREATE DATABASE IF NOT EXISTS. This SELECT produces
-- the text of a CREATE DATABASE statement only when lecture04 doesn't
-- exist, and \gexec runs whatever text the SELECT produced.
SELECT 'CREATE DATABASE lecture04'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'lecture04')\gexec

\c lecture04

-- Also drops the star schema built in the demo's Part 6, so this stays
-- the reset button.
DROP TABLE IF EXISTS fact_sales, dim_date, dim_customer, dim_product, dim_employee,
                     order_items, sales, orders, customers, employees, products;

-- ---- The flat file: one wide table, one row per order line ----
CREATE TABLE sales (
    orderID              INT,
    orderDate            DATE,
    orderTime            TIME,
    channel              VARCHAR(10),      -- in_store / online
    status               VARCHAR(10),      -- completed / returned / cancelled
    paymentMethod        VARCHAR(10),      -- cash / card / transfer
    deliveryDate         DATE,             -- online orders only
    rating               INT,              -- 1-5, when the customer bothered
    orderTotal           DECIMAL(10,2),    -- the WHOLE order's total, repeated on each of its lines
    quantity             INT,
    unitPrice            DECIMAL(8,2),
    discountPct          INT,
    lineTotal            DECIMAL(10,2),    -- this line only
    customerFirstName    VARCHAR(50),
    customerLastName     VARCHAR(50),
    customerEmail        VARCHAR(100),
    customerCity         VARCHAR(50),
    customerBirthDate    DATE,
    customerSignupDate   DATE,
    customerAnniversary  DATE,
    customerMoneySpent   DECIMAL(10,2),
    employeeFirstName    VARCHAR(50),      -- empty for online orders
    employeeLastName     VARCHAR(50),
    employeePosition     VARCHAR(30),
    employeeBranch       VARCHAR(50),
    productName          VARCHAR(100),
    productCategory      VARCHAR(50),
    productBrand         VARCHAR(50),
    productPrice         DECIMAL(8,2),
    productCost          DECIMAL(8,2)
);

CREATE TABLE customers (
    customerID   SERIAL PRIMARY KEY,
    firstName    VARCHAR(50)  NOT NULL,
    lastName     VARCHAR(50)  NOT NULL,
    email        VARCHAR(100) NOT NULL UNIQUE,
    phone        VARCHAR(20),
    city         VARCHAR(50)  NOT NULL,
    birthDate    DATE,
    signupDate   DATE         NOT NULL,
    anniversary  DATE,
    moneySpent   DECIMAL(10,2) NOT NULL DEFAULT 0 CHECK (moneySpent >= 0)
);

CREATE TABLE employees (
    employeeID   SERIAL PRIMARY KEY,
    firstName    VARCHAR(50)  NOT NULL,
    lastName     VARCHAR(50)  NOT NULL,
    email        VARCHAR(100) NOT NULL UNIQUE,
    birthDate    DATE,
    hireDate     DATE         NOT NULL,
    position     VARCHAR(30)  NOT NULL,
    branch       VARCHAR(50)  NOT NULL,
    salary       DECIMAL(8,2) NOT NULL CHECK (salary > 0),
    managerID    INT REFERENCES employees(employeeID)   -- who this person reports to; NULL = nobody
);

CREATE TABLE products (
    productID      SERIAL PRIMARY KEY,
    productName    VARCHAR(100) NOT NULL,
    category       VARCHAR(50)  NOT NULL,
    brand          VARCHAR(50)  NOT NULL,
    price          DECIMAL(8,2) NOT NULL CHECK (price >= 0),
    cost           DECIMAL(8,2) NOT NULL CHECK (cost  >= 0),
    stockQuantity  INT          NOT NULL DEFAULT 0 CHECK (stockQuantity >= 0),
    isActive       BOOLEAN      NOT NULL DEFAULT TRUE,
    UNIQUE (productName, brand)
);

-- ---- The order header: one row per order ----
CREATE TABLE orders (
    orderID        INT PRIMARY KEY,
    customerID     INT NOT NULL REFERENCES customers(customerID),
    employeeID     INT          REFERENCES employees(employeeID),   -- NULL = online, nobody served it
    orderDate      DATE NOT NULL,
    orderTime      TIME NOT NULL,
    channel        VARCHAR(10) NOT NULL CHECK (channel IN ('in_store', 'online')),
    paymentMethod  VARCHAR(10) NOT NULL CHECK (paymentMethod IN ('cash', 'card', 'transfer')),
    status         VARCHAR(10) NOT NULL CHECK (status IN ('completed', 'returned', 'cancelled')),
    deliveryDate   DATE,
    rating         INT CHECK (rating BETWEEN 1 AND 5),
    orderTotal     DECIMAL(10,2) NOT NULL CHECK (orderTotal >= 0)   -- = sum of the order's lineTotals
);

-- ---- The order lines: one row per product in an order ----
CREATE TABLE order_items (
    orderID      INT NOT NULL REFERENCES orders(orderID),
    productID    INT NOT NULL REFERENCES products(productID),
    quantity     INT NOT NULL CHECK (quantity > 0),
    unitPrice    DECIMAL(8,2) NOT NULL CHECK (unitPrice >= 0),
    discountPct  INT NOT NULL DEFAULT 0 CHECK (discountPct BETWEEN 0 AND 100),
    lineTotal    DECIMAL(10,2) NOT NULL CHECK (lineTotal >= 0),     -- quantity x unitPrice, minus the discount
    PRIMARY KEY (orderID, productID)
);

-- ---- Load. Parents before children -- the foreign keys insist. ----
-- (CSV fallback: replace the six \copy lines with  \i data/all_inserts.sql)
-- An empty field in a CSV (no anniversary, no employee, no rating) becomes NULL.
\copy sales       FROM 'data/sales_flat.csv'  WITH (FORMAT csv, HEADER true)
\copy customers   FROM 'data/customers.csv'   WITH (FORMAT csv, HEADER true)
-- employees.csv has no managerID column, so name the columns it does have.
\copy employees (employeeID, firstName, lastName, email, birthDate, hireDate, position, branch, salary) FROM 'data/employees.csv' WITH (FORMAT csv, HEADER true)
\copy products    FROM 'data/products.csv'    WITH (FORMAT csv, HEADER true)
\copy orders      FROM 'data/orders.csv'      WITH (FORMAT csv, HEADER true)
\copy order_items FROM 'data/order_items.csv' WITH (FORMAT csv, HEADER true)

-- The CSVs carry their own ids, so each SERIAL counter still thinks the
-- next id is 1. Move them past what's loaded, or the first INSERT
-- without an id would collide with row 1.
SELECT setval(pg_get_serial_sequence('customers', 'customerid'), (SELECT max(customerID) FROM customers));
SELECT setval(pg_get_serial_sequence('employees', 'employeeid'), (SELECT max(employeeID) FROM employees));
SELECT setval(pg_get_serial_sequence('products',  'productid'),  (SELECT max(productID)  FROM products));

-- ---- The reporting line ----
-- Vahe runs the Yerevan Center store and everyone reports up to him.
-- The two other branches have a Senior Sales lead in between.
UPDATE employees SET managerID = 3 WHERE employeeID IN (1, 2, 5, 8);   -- Gor, Ani, Hayk, Marine -> Vahe
UPDATE employees SET managerID = 5 WHERE employeeID IN (4, 6);         -- Nare, Lilit -> Hayk (Yerevan Mall)
UPDATE employees SET managerID = 8 WHERE employeeID = 7;               -- Arman -> Marine (Gyumri)

-- Collect table statistics now instead of waiting for autovacuum, so
-- the planner sees the same numbers on every machine.
ANALYZE;

-- Expect 965 / 30 / 8 / 37 / 600 / 965
SELECT 'sales' AS t, count(*) FROM sales
UNION ALL SELECT 'customers',   count(*) FROM customers
UNION ALL SELECT 'employees',   count(*) FROM employees
UNION ALL SELECT 'products',    count(*) FROM products
UNION ALL SELECT 'orders',      count(*) FROM orders
UNION ALL SELECT 'order_items', count(*) FROM order_items;



-- ============================================================
-- Lecture 4 — Part 1: data models
-- Run after Part 0.
-- ============================================================

-- ---- The physical level: how this engine stores orders ----
-- Exact types, constraints, defaults -- and the primary-key index
-- PostgreSQL built by itself (orders_pkey).
\d orders



-- ============================================================
-- Lecture 4 — Part 2: order_items, the junction table
-- Run after Part 0.
-- ============================================================

-- ---- order_items: the table Lecture 2 deferred ----
-- An order can hold several products. orders is now the HEADER (one row
-- per order); the products sit on the LINES, one row per product in an
-- order, keyed by (orderID, productID).
SELECT count(*) AS orders FROM orders;
--  orders
-- --------
--     600

SELECT count(*) AS lines FROM order_items;
--  lines
-- -------
--    965

-- How many lines do orders have?
SELECT lines, count(*) AS orders
FROM (SELECT orderID, count(*) AS lines FROM order_items GROUP BY orderID) AS t
GROUP BY lines
ORDER BY lines;
--  lines | orders
-- -------+--------
--      1 |    365
--      2 |    133
--      3 |     74
--      4 |     28

-- The order total is the sum of its lines -- checked, not assumed:
SELECT count(*) AS orders_where_total_disagrees
FROM orders o
JOIN (SELECT orderID, sum(lineTotal) AS lines_total FROM order_items GROUP BY orderID) AS l
  ON l.orderID = o.orderID
WHERE o.orderTotal <> l.lines_total;
--  orders_where_total_disagrees
-- ------------------------------
--                             0



-- ============================================================
-- Lecture 4 — Part 3: JOINs, step by step
-- The files steps/01 ... steps/15, in order. Read-only.
-- ============================================================




-- ============================================================
-- Lecture 4 — Joins, step 1: CROSS JOIN, and the one idea
-- Notes: Part 4.0 and 4.1
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- THE ONE IDEA, before any syntax:
--   A join is: pair every row of A with every row of B,
--   then keep the pairs you want.
--
-- Every join type in this lecture is a variation on two questions:
-- which pairs do we keep, and what do we do with the rows that found
-- no pair? CROSS JOIN is the starting point: it keeps ALL the pairs.
-- ============================================================


-- ---- 1. Every pair: the whole Cartesian product ----
-- Guess first: orders has 600 rows, customers has 30. How many rows?
SELECT count(*) FROM orders CROSS JOIN customers;
--  count
-- -------
--  18000
-- No order belongs to 30 customers. Almost every one of these pairs is
-- nonsense. That's the point: this is the raw material every other
-- join is carved out of.


-- ---- 2. CROSS JOIN is not a special case ----
-- PostgreSQL defines  A CROSS JOIN B  as exactly  A INNER JOIN B ON TRUE:
-- a join whose condition can never fail. The old comma syntax is the
-- same thing again. All three return the same count:
SELECT count(*) FROM orders INNER JOIN customers ON TRUE;
--  count
-- -------
--  18000
SELECT count(*) FROM orders, customers;
--  count
-- -------
--  18000


-- ---- 3. Zoom in: 3 orders × 3 customers = 9 pairs ----
-- The same product, small enough to read. Orders 1001-1003 were placed
-- by customers 2, 26 and 6, so take exactly those three customers.
SELECT o.orderID,
       o.customerID AS "order says",
       c.customerID AS "customer row",
       c.firstName, c.lastName
FROM orders o CROSS JOIN customers c
WHERE o.orderID IN (1001, 1002, 1003)
  AND c.customerID IN (2, 6, 26)
ORDER BY o.orderID, c.customerID;
--  orderid | order says | customer row | firstname | lastname
-- ---------+------------+--------------+-----------+-----------
-- ... 9 rows
-- Ask the room: which pairs are true? The ones where the number the
-- order holds equals the customer's id.


-- ---- 4. Keep only the pairs you want: add the matching condition ----
SELECT o.orderID,
       o.customerID AS "order says",
       c.customerID AS "customer row",
       c.firstName, c.lastName
FROM orders o CROSS JOIN customers c
WHERE o.orderID IN (1001, 1002, 1003)
  AND c.customerID IN (2, 6, 26)
  AND o.customerID = c.customerID
ORDER BY o.orderID;
--  orderid | order says | customer row | firstname | lastname
-- ---------+------------+--------------+-----------+-----------
--     1001 |          2 |            2 | Davit     | Petrosyan
--     1002 |         26 |           26 | Samvel    | Nazaryan
--     1003 |          6 |            6 | Narek     | Manukyan
-- That IS a join: every pair, filtered down to the pairs whose values
-- match. Nothing more mysterious than that.


-- ---- 5. The same result, written as JOIN ... ON ----
-- ON puts the matching condition next to the table it's about.
-- JOIN on its own means INNER JOIN.
SELECT o.orderID, c.firstName, c.lastName, o.orderTotal
FROM orders o
JOIN customers c ON c.customerID = o.customerID
WHERE o.orderID IN (1001, 1002, 1003)
ORDER BY o.orderID;
--  orderid | firstname | lastname  | ordertotal
-- ---------+-----------+-----------+------------
--     1001 | Davit     | Petrosyan |     211.65
--     1002 | Samvel    | Nazaryan  |     249.00
--     1003 | Narek     | Manukyan  |     747.00
-- Does PostgreSQL really build 18,000 pairs and throw most away? No:
-- the planner picks a nested-loop, merge or hash join by estimated
-- cost. But every plan returns exactly what the slow "every pair, then
-- filter" method would. Think the slow way; let the database do the
-- fast one.



-- ============================================================
-- Lecture 4 — Joins, step 2: INNER JOIN keeps only pairs that match
-- Notes: Part 4.2
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- A INNER JOIN B ON condition = from all possible pairs, keep only the
-- ones where the condition is true. A row on either side with no
-- partner at all simply disappears: no error, no placeholder, gone.
-- ============================================================


-- ---- 1. Each JOIN adds one more lookup ----
-- A join's result is a table, and you can join that to the next table.
-- Every order has exactly one customer, so this keeps one row per order:
SELECT count(*)
FROM orders o
JOIN customers c ON c.customerID = o.customerID;
--  count
-- -------
--    600


-- ---- 2. Joining the LINES changes what a row is ----
-- Products don't live on the order any more: an order can hold several,
-- one row each in order_items. To see them, go through the lines:
-- orders -> order_items -> products.
SELECT o.orderID, o.orderDate,
       c.firstName || ' ' || c.lastName AS customer,
       p.productName, i.quantity, i.lineTotal,
       o.orderTotal
FROM orders o
JOIN customers   c ON c.customerID = o.customerID
JOIN order_items i ON i.orderID    = o.orderID
JOIN products    p ON p.productID  = i.productID
WHERE o.orderID IN (1001, 1009)
ORDER BY o.orderID, p.productName;
--  orderid | orderdate  |     customer     |    productname    | quantity | linetotal | ordertotal
-- ---------+------------+------------------+-------------------+----------+-----------+------------
--     1001 | 2024-01-01 | Davit Petrosyan  | AirPods Pro       |        1 |    211.65 |     211.65
--     1009 | 2024-01-08 | Tigran Grigoryan | HDMI 2.1 Cable 2m |        2 |     20.64 |     147.76
--     1009 | 2024-01-08 | Tigran Grigoryan | LaserJet M110     |        1 |    119.20 |     147.76
--     1009 | 2024-01-08 | Tigran Grigoryan | USB-C Cable 1m    |        1 |      7.92 |     147.76
-- Order 1001 has one line; order 1009 has three. Look at orderTotal:
-- 1009's whole total sits on EVERY one of its lines, while lineTotal is
-- each line's own share. Remember that for step 11.

-- Guess first: there are 600 orders. How many rows does the full join give?
SELECT count(*)
FROM orders o
JOIN customers   c ON c.customerID = o.customerID
JOIN order_items i ON i.orderID    = o.orderID
JOIN products    p ON p.productID  = i.productID;
--  count
-- -------
--    965
-- Nothing was lost: one row per LINE. Every join answers "one row per
-- what?", and joining a one-to-many table changes the answer.


-- ---- 3. Add employees: where did 181 orders go? ----
-- Back to one row per order. Guess first: how many rows now?
SELECT count(*)
FROM orders o
JOIN customers c ON c.customerID = o.customerID
JOIN employees e ON e.employeeID = o.employeeID;
--  count
-- -------
--    419

-- The missing 181 are exactly the online orders. Their employeeID is
-- NULL, and NULL equals nothing, so they can't satisfy
-- o.employeeID = e.employeeID for ANY employee. An inner join drops
-- every row that can't find a partner.
SELECT count(*) FILTER (WHERE employeeID IS NULL) AS online_orders,
       count(*)                                   AS all_orders
FROM orders;
--  online_orders | all_orders
-- ---------------+------------
--            181 |        600

-- Drill this until it's automatic:
--   An inner join doesn't complain when rows don't match —
--   it just quietly leaves them out.


-- ---- 4. Why that matters: a real sum over the wrong rows ----
-- "Completed revenue, with the salesperson's name." Someone joined
-- employees just to have the names:
SELECT sum(o.orderTotal) AS revenue
FROM orders o
JOIN employees e ON e.employeeID = o.employeeID
WHERE o.status = 'completed';
--   revenue
-- -----------
--  100222.48

-- The same question without the join:
SELECT sum(orderTotal) AS revenue
FROM orders
WHERE status = 'completed';
--   revenue
-- -----------
--  157078.41
-- 100,222.48 is a real sum, correctly computed — over a silently
-- incomplete set of rows. 56,855.93 of web-shop revenue vanished.
-- That's not a bug in PostgreSQL; it's the definition of inner join.
-- It's just invisible unless you go looking. Step 5 shows the fix.



-- ============================================================
-- Lecture 4 — Joins, step 3: aliasing, and the two errors that teach it
-- Notes: Part 4.3
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
-- TWO statements in this file fail ON PURPOSE. Read each error.
-- ============================================================


-- ---- 1. Full table names work, but they're long ----
SELECT orders.orderID, customers.firstName, orders.orderTotal
FROM orders
JOIN customers ON customers.customerID = orders.customerID
WHERE orders.orderID = 1001;
--  orderid | firstname | ordertotal
-- ---------+-----------+------------
--     1001 | Davit     |     211.65


-- ---- 2. Error on purpose: an ambiguous column ----
-- customerID exists in BOTH orders and customers. Which one do you mean?
SELECT orderID, customerID, firstName
FROM orders
JOIN customers ON customers.customerID = orders.customerID
WHERE orderID = 1001;
-- ERROR:  column reference "customerid" is ambiguous
-- orderID and firstName exist in only one table each, so PostgreSQL
-- finds them. customerID exists in two, and the engine refuses to
-- guess — even though the two values are equal on every joined row.
-- The rule is about NAMES, not values.


-- ---- 3. The fix: alias the tables, qualify the columns ----
SELECT o.orderID, o.customerID, c.firstName
FROM orders o
JOIN customers c ON c.customerID = o.customerID
WHERE o.orderID = 1001;
--  orderid | customerid | firstname
-- ---------+------------+-----------
--     1001 |          2 | Davit


-- ---- 4. Error on purpose: the alias REPLACED the name ----
-- Once you write FROM orders o, the name "orders" stops existing for
-- the rest of that query. Only "o" does.
SELECT orders.orderID
FROM orders o
WHERE o.orderID = 1001;
-- ERROR:  invalid reference to FROM-clause entry for table "orders"
-- HINT:  Perhaps you meant to reference the table alias "o".
-- Read the HINT: PostgreSQL tells you exactly what happened. An alias
-- doesn't add a nickname — it replaces the name.


-- ---- The habit ----
-- In any query with two or more tables, prefix EVERY column, even the
-- ones that aren't ambiguous yet. Next month someone adds a firstName
-- column to orders, and every unprefixed query breaks.



-- ============================================================
-- Lecture 4 — Joins, step 4: USING, and why NATURAL JOIN is dangerous
-- Notes: Part 4.4
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
-- ============================================================


-- ---- 1. USING: shorthand when the key has the same name on both sides ----
-- USING (customerID)  means  ON o.customerID = c.customerID
SELECT customerID, c.firstName, o.orderID
FROM orders o
JOIN customers c USING (customerID)
WHERE o.orderID = 1001;
--  customerid | firstname | orderid
-- ------------+-----------+---------
--           2 | Davit     |    1001
-- Bonus: USING merges the two customerID columns into ONE output
-- column, so the bare "customerID" in SELECT is no longer ambiguous
-- (compare step 3's error).


-- ---- 2. NATURAL JOIN: joins on every shared column name ----
-- sales is the flat file: one row per order LINE, with the order's
-- columns copied onto each line. Joined honestly on orderID, every line
-- finds its order:
SELECT count(*) FROM orders o JOIN sales s ON s.orderID = o.orderID;
--  count
-- -------
--    965
-- Guess first: what does NATURAL JOIN give?
SELECT count(*) FROM orders NATURAL JOIN sales;
--  count
-- -------
--    168


-- ---- 3. Why so few? See which columns it silently joined on ----
-- NATURAL JOIN uses EVERY column name the two tables share:
SELECT column_name FROM information_schema.columns WHERE table_name = 'orders'
INTERSECT
SELECT column_name FROM information_schema.columns WHERE table_name = 'sales'
ORDER BY 1;
--   column_name
-- ---------------
-- ... 9 rows
-- All nine had to be equal. deliveryDate is NULL for every in-store
-- order, rating is NULL for many orders — and NULL = NULL is not true
-- (Lecture 3's NULL rule). Any row with a NULL in any of the nine is
-- thrown out. The survivors are the lines of online orders that also
-- got a rating:
SELECT count(*)
FROM sales
WHERE deliveryDate IS NOT NULL
  AND rating IS NOT NULL;
--  count
-- -------
--    168


-- ---- The one-line takeaway ----
-- The join condition should always be visible in the code you read.
-- NATURAL JOIN hides it — and it changes by itself, without warning,
-- the day either table gains a new column with a matching name.
-- Never use it in real code. Write ON, or USING when the names match.



-- ============================================================
-- Lecture 4 — Joins, step 5: LEFT, RIGHT and FULL outer joins
-- Notes: Part 4.5
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- Build it up as: INNER JOIN, but we refuse to lose rows from one
-- side (or both). Where a row has no partner, keep it anyway and fill
-- the missing side with NULLs.
-- ============================================================


-- ---- 1. LEFT JOIN: every row of the LEFT table, at least once ----
-- "Left" = the table written before the word JOIN.
SELECT o.orderID, o.channel, e.firstName, e.branch
FROM orders o
LEFT JOIN employees e ON e.employeeID = o.employeeID
WHERE o.orderID BETWEEN 1001 AND 1008
ORDER BY o.orderID;
--  orderid | channel  | firstname |     branch
-- ---------+----------+-----------+----------------
-- ... 8 rows

SELECT count(*)
FROM orders o
LEFT JOIN employees e ON e.employeeID = o.employeeID;
--  count
-- -------
--    600


-- ---- 2. Give the NULLs a name, and the lost revenue comes back ----
SELECT coalesce(e.branch, 'Online') AS branch,
       count(*)                     AS orders,
       sum(o.orderTotal)            AS revenue
FROM orders o
LEFT JOIN employees e ON e.employeeID = o.employeeID
WHERE o.status = 'completed'
GROUP BY coalesce(e.branch, 'Online')
ORDER BY revenue DESC;
--      branch     | orders | revenue
-- ----------------+--------+----------
--  Online         |    164 | 56855.93
--  Yerevan Center |    187 | 51758.15
--  Yerevan Mall   |    133 | 38008.16
--  Gyumri         |     45 | 10456.17


-- ---- 3. RIGHT JOIN: the mirror image ----
-- A RIGHT JOIN B keeps every row of B — which makes it B LEFT JOIN A.
SELECT count(*)
FROM orders o
RIGHT JOIN customers c ON c.customerID = o.customerID;
--  count
-- -------
--    602

SELECT count(*)
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID;
--  count
-- -------
--    602
-- Why 602 and not 600? Two customers have no orders; each is kept as
-- one NULL-padded row. Step 6 finds them. This course always writes
-- LEFT (put the table you want to keep first) so every query reads
-- the same way. Know RIGHT for when you meet it in someone else's code.


-- ---- 4. FULL JOIN: keep everything from both sides ----
-- LEFT and RIGHT combined. Its classic use is reconciling two lists.
-- Here: compare the customer list with the staff list, by name.
SELECT CASE WHEN e.employeeID IS NULL THEN 'customer only'
            WHEN c.customerID IS NULL THEN 'employee only'
            ELSE 'on both lists' END AS status,
       count(*) AS people
FROM customers c
FULL JOIN employees e ON e.firstName = c.firstName AND e.lastName = c.lastName
GROUP BY 1
ORDER BY 1;
--     status     | people
-- ---------------+--------
--  customer only |     28
--  employee only |      6
--  on both lists |      2
-- 28 + 6 + 2 = 36: the 30 customers and 8 employees, with the matched
-- pairs counted once. Hold on to those 2 "on both lists" — step 10
-- asks who they really are.



-- ============================================================
-- Lecture 4 — Joins, step 6: the anti-join — "which X have no Y?"
-- Notes: Part 4.5 (anti-join)
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- The single most useful LEFT JOIN pattern:
--     LEFT JOIN  +  WHERE right.key IS NULL
-- A real match would fill the right-hand columns. If they are NULL,
-- the left-hand row had nothing to match.
-- ============================================================


-- ---- 1. Customers who never ordered ----
SELECT c.customerID, c.firstName, c.lastName, c.signupDate
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
WHERE o.orderID IS NULL;
--  customerid | firstname | lastname  | signupdate
-- ------------+-----------+-----------+------------
--          24 | Levon     | Arakelyan | 2023-11-01
--          29 | Astghik   | Danielyan | 2022-10-23


-- ---- 2. Products never ordered ----
-- Products appear on order LINES, so the right-hand table is order_items.
SELECT p.productID, p.productName, p.category, p.stockQuantity
FROM products p
LEFT JOIN order_items i ON i.productID = p.productID
WHERE i.orderID IS NULL;
--  productid |     productname     | category | stockquantity
-- -----------+---------------------+----------+---------------
--         35 | Ergonomic Chair Pro | Chairs   |             6


-- ---- 3. Why test the right table's KEY? ----
-- o.orderID is orders' primary key: in a real row it can never be
-- NULL. So "o.orderID IS NULL" can only mean "no row matched".
-- Testing a column that CAN be NULL in real rows (say o.rating) would
-- also catch orders that simply have no rating — wrong answer:
SELECT count(*)
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
WHERE o.rating IS NULL;
--  count
-- -------
--    280


-- ---- Teach it as a named pattern ----
-- "Which X have no Y" comes up constantly: customers with no orders,
-- products never sold, employees with no reports. The flat sales
-- table could never answer these — a table of sales only contains
-- things that sold.



-- ============================================================
-- Lecture 4 — Joins, step 7: count(*) vs count(column)
-- Notes: Part 4.6
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- count(*)       counts rows that exist.
-- count(column)  counts rows where that column is NOT NULL.
-- After a LEFT JOIN the two should diverge exactly at the unmatched
-- rows. Run both, every time, right after writing an outer join.
-- ============================================================


-- ---- 1. Orders per customer, fewest first — with count(*) ----
SELECT c.firstName, c.lastName, count(*) AS orders
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
GROUP BY c.customerID, c.firstName, c.lastName
ORDER BY orders, c.lastName
LIMIT 4;
--  firstname |  lastname  | orders
-- -----------+------------+--------
--  Levon     | Arakelyan  |      1
--  Astghik   | Danielyan  |      1
--  Diana     | Aleksanyan |      4
--  Lusine    | Avetisyan  |      5
-- The LEFT JOIN gave Levon one row, full of NULLs. count(*) counts it.


-- ---- 2. The same query with count(o.orderID) ----
SELECT c.firstName, c.lastName, count(o.orderID) AS orders
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
GROUP BY c.customerID, c.firstName, c.lastName
ORDER BY orders, c.lastName
LIMIT 4;
--  firstname |  lastname  | orders
-- -----------+------------+--------
--  Levon     | Arakelyan  |      0
--  Astghik   | Danielyan  |      0
--  Diana     | Aleksanyan |      4
--  Lusine    | Avetisyan  |      5


-- ---- 3. The reflex: both counts side by side ----
SELECT count(*)          AS joined_rows,
       count(o.orderID)  AS real_matches
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID;
--  joined_rows | real_matches
-- -------------+--------------
--          602 |          600
-- The two counts should differ by exactly the number of unmatched
-- customers from step 6. If the gap isn't the number you expect,
-- something about the join is wrong — find out before trusting
-- anything built on top of it.



-- ============================================================
-- Lecture 4 — Joins, step 8: the WHERE-vs-ON trap
-- Notes: Part 4.7 — the most important trap in the lecture
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- With inner joins it doesn't matter whether a condition sits in ON
-- or in WHERE. With outer joins it matters completely, because of
-- WHEN each one runs:
--   ON     applies while deciding what matches — before the outer join
--          NULL-pads the unmatched rows.
--   WHERE  applies after the whole join, NULL-padding included — so it
--          can delete the very rows the LEFT JOIN just protected.
--
-- "ON decides who gets invited to the party. WHERE decides who's
--  allowed to stay after it already happened — including the guests
--  the LEFT JOIN invited for free (the NULL-padded ones)."
-- ============================================================


-- ---- 1. Revenue per category, including categories that sold nothing ----
-- Revenue lives on the lines (lineTotal), so go products -> lines.
SELECT p.category, count(i.orderID) AS lines, sum(i.lineTotal) AS revenue
FROM products p
LEFT JOIN order_items i ON i.productID = p.productID
GROUP BY p.category
ORDER BY revenue DESC NULLS LAST;
--   category   | lines | revenue
-- -------------+-------+----------
-- ... 13 rows
-- Look for Chairs: it never sold, but the LEFT JOIN keeps it.


-- ---- 2. The boss adds "completed orders only". The obvious edit: ----
-- status lives on the order header, so join orders too, and filter:
SELECT p.category, count(i.orderID) AS lines, sum(i.lineTotal) AS revenue
FROM products p
LEFT JOIN order_items i ON i.productID = p.productID
LEFT JOIN orders      o ON o.orderID   = i.orderID
WHERE o.status = 'completed'
GROUP BY p.category
ORDER BY revenue DESC NULLS LAST;
--   category   | lines | revenue
-- -------------+-------+----------
-- ... 12 rows
-- Walk the order: the LEFT JOINs run first and keep the Chair row,
-- with o.status NULL. Then WHERE runs: NULL = 'completed' is not true,
-- so the Chair row is thrown out along with the genuinely
-- non-completed rows. The LEFT JOIN has quietly become an INNER JOIN.


-- ---- 3. Move the condition into ON — but which ON? ----
-- First attempt: into the ON of the orders join.
SELECT p.category, count(i.orderID) AS lines, coalesce(sum(i.lineTotal), 0) AS revenue
FROM products p
LEFT JOIN order_items i ON i.productID = p.productID
LEFT JOIN orders      o ON o.orderID   = i.orderID
                       AND o.status    = 'completed'
GROUP BY p.category
ORDER BY revenue DESC;
--   category   | lines | revenue
-- -------------+-------+----------
-- ... 13 rows
-- Chairs is back. But compare the revenue with query 2: it went UP.
-- The status test now only decides whether a line finds its ORDER.
-- A line of a returned order still exists — it just gets NULL order
-- columns — and its lineTotal is still summed. This is part 1's
-- all-orders revenue again, wearing a "completed" label.


-- ---- 4. The fix: decide what counts as a match BEFORE the LEFT JOIN ----
-- A product's match is "a line of a completed order". Build exactly
-- that inside the brackets (an inner join: lines + their completed
-- order), then LEFT JOIN products to the result.
SELECT p.category, count(i.orderID) AS lines, coalesce(sum(i.lineTotal), 0) AS revenue
FROM products p
LEFT JOIN (order_items i
           JOIN orders o ON o.orderID = i.orderID
                        AND o.status  = 'completed')
       ON i.productID = p.productID
GROUP BY p.category
ORDER BY revenue DESC;
--   category   | lines | revenue
-- -------------+-------+----------
-- ... 13 rows
-- Every category from query 2 with the same revenue, AND Chairs at 0.
-- (coalesce turns the NULL sum into 0: sum of no rows is NULL.)
-- With one LEFT JOIN, "move it into ON" is the whole fix. With a chain
-- of joins, ask which join the condition belongs to.


-- ---- 5. The other half of the rule: left-table conditions ----
-- Intent: "Gyumri customers and their orders."
-- Wrong: the left-table condition placed in ON.
SELECT count(*) AS rows, count(o.orderID) AS matched
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
                  AND c.city = 'Gyumri';
--  rows | matched
-- ------+---------
--   233 |     210
-- A LEFT JOIN keeps EVERY left row, so every customer is still there:
-- the Gyumri customers with their orders, plus one NULL-padded row
-- for each customer from anywhere else.

-- Right: the left-table condition in WHERE.
SELECT count(*) AS rows, count(o.orderID) AS matched
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
WHERE c.city = 'Gyumri';
--  rows | matched
-- ------+---------
--   210 |     210


-- ---- The rule to remember ----
--   conditions on the RIGHT table of a LEFT JOIN  ->  ON
--   conditions on the LEFT table                  ->  WHERE
-- A WHERE that mentions the right-hand table after a LEFT JOIN should
-- always make you stop and ask: am I filtering matches, or un-inviting
-- the rows my LEFT JOIN was supposed to protect?



-- ============================================================
-- Lecture 4 — Joins, step 9: self-joins — a table joined to itself
-- Notes: Part 4.8
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
-- ONE statement in this file fails ON PURPOSE.
--
-- employees.managerID points at another row of employees (filled in
-- by steps/00-setup.sql). Same table, two roles — so two aliases.
-- ============================================================


-- ---- 0. Look at the raw data first ----
SELECT employeeID, firstName, position, branch, managerID
FROM employees
ORDER BY employeeID;
--  employeeid | firstname |    position     |     branch     | managerid
-- ------------+-----------+-----------------+----------------+-----------
-- ... 8 rows


-- ---- 1. Error on purpose: a self-join without aliases ----
SELECT employees.firstName, employees.firstName
FROM employees
JOIN employees ON employees.employeeID = employees.managerID;
-- ERROR:  table name "employees" specified more than once
-- There is no way to say "this row" and "that other row of the same
-- table" without giving each copy its own name.


-- ---- 2. Direct manager: e plays the employee, m plays the manager ----
SELECT e.firstName || ' ' || e.lastName AS employee,
       e.position,
       m.firstName || ' ' || m.lastName AS manager
FROM employees e
LEFT JOIN employees m ON m.employeeID = e.managerID
ORDER BY m.employeeID NULLS FIRST, e.employeeID;
--       employee      |    position     |    manager
-- --------------------+-----------------+----------------
-- ... 8 rows
-- Why LEFT? Guess what an inner join would do: 7 rows — the boss,
-- whose managerID is NULL, would vanish from the staff list.


-- ---- 3. A second hop: the manager's manager ----
SELECT e.firstName AS employee, m.firstName AS manager, mm.firstName AS managers_manager
FROM employees e
LEFT JOIN employees m  ON m.employeeID  = e.managerID
LEFT JOIN employees mm ON mm.employeeID = m.managerID
WHERE e.branch <> 'Yerevan Center';
--  employee | manager | managers_manager
-- ----------+---------+------------------
--  Hayk     | Vahe    |
--  Marine   | Vahe    |
--  Nare     | Hayk    | Vahe
--  Lilit    | Hayk    | Vahe
--  Arman    | Marine  | Vahe
-- Two levels up took two joins. "All the way up, however many levels"
-- would need one join per level.


-- ---- 4. Self-join + GROUP BY: direct reports per manager ----
SELECT m.firstName || ' ' || m.lastName AS manager, count(e.employeeID) AS direct_reports
FROM employees m
JOIN employees e ON e.managerID = m.employeeID
GROUP BY m.employeeID, m.firstName, m.lastName
ORDER BY direct_reports DESC;
--     manager     | direct_reports
-- ----------------+----------------
--  Vahe Sahakyan  |              4
--  Hayk Melikyan  |              2
--  Marine Avagyan |              1
-- An inner join on purpose: only people who manage someone appear.

-- Any hierarchy stored as "this table points to itself" — org charts,
-- category trees, comment replies — uses exactly this shape.



-- ============================================================
-- Lecture 4 — Joins, step 10: joining on the wrong thing
-- Notes: Part 4.9 — names are not identifiers
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
-- ============================================================


-- ---- 1. "Which of our employees also shop with us?" ----
-- Step 5's FULL JOIN found 2 names on both lists. Join on the names:
SELECT c.firstName, c.lastName,
       c.birthDate AS customer_born, e.birthDate AS employee_born,
       c.city      AS customer_city, e.branch    AS employee_branch
FROM customers c
JOIN employees e ON e.firstName = c.firstName AND e.lastName = c.lastName;
--  firstname |   lastname   | customer_born | employee_born | customer_city | employee_branch
-- -----------+--------------+---------------+---------------+---------------+-----------------
--  Hayk      | Melikyan     | 1993-03-30    | 1985-02-11    | Vanadzor      | Yerevan Mall
--  Lilit     | Hovhannisyan | 1990-06-14    | 1998-07-07    | Abovyan       | Yerevan Mall
-- Read the birth dates: these are FOUR different people. The join did
-- exactly what it was told — it matched names. The honest answer to
-- the question is: this data can't tell. No column links a customer
-- to an employee.


-- ---- 2. The same mistake at scale: rows multiply ----
-- Try to give each flat sales row its customerID by looking the name
-- up in customers. The flat file has one row per order line:
SELECT count(*) AS sales_rows FROM sales;
--  sales_rows
-- ------------
--         965
-- Guess first: that many rows in. How many come out of the name join?
SELECT count(*)
FROM sales s
JOIN customers c ON c.firstName = s.customerFirstName
                AND c.lastName  = s.customerLastName;
--  count
-- -------
--   1036

-- Where do the extra rows come from? Two customers are both named
-- Anna Sargsyan. Every sales row for either Anna matches BOTH, so each
-- of these rows comes out twice:
SELECT count(*) AS anna_rows
FROM sales
WHERE customerFirstName = 'Anna' AND customerLastName = 'Sargsyan';
--  anna_rows
-- -----------
--         71

-- The fix: join on something guaranteed unique. customers.email has a
-- UNIQUE constraint, and the flat file carries each customer's email:
SELECT count(*)
FROM sales s
JOIN customers c ON c.email = s.customerEmail;
--  count
-- -------
--    965
-- One customer per email, so every sales row finds exactly one partner.


-- ---- The one-line lesson ----
-- Only join on something GUARANTEED unique — a real key. Anything that
-- merely "usually" identifies a row correctly will eventually produce
-- a false match once the data is large enough, and the join won't
-- warn you when it happens.



-- ============================================================
-- Lecture 4 — Joins, step 11: the fan-out trap
-- Notes: Part 4.10 — the most damaging trap, because the number
-- looks completely normal
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- It needs no outer join and no strange join type. A completely
-- ordinary inner join breaks it.
-- ============================================================


-- ---- 1. The question: total lifetime spend of our customers ----
-- customers.moneySpent is one number per customer (customer grain).
-- Someone joins orders "to make sure we only count real buyers":
SELECT sum(c.moneySpent) AS total_customer_spend
FROM customers c
JOIN orders o ON o.customerID = c.customerID;
--  total_customer_spend
-- ----------------------
--            4386925.27
-- Ask the room: does that look plausible? Nothing is red. No error.


-- ---- 2. The real total ----
SELECT sum(moneySpent) AS total_customer_spend
FROM customers;
--  total_customer_spend
-- ----------------------
--             157078.41


-- ---- 3. Why: one value copied onto every matching row ----
-- orders has many rows per customer (order grain). The join copies
-- each customer's moneySpent onto EVERY one of their order rows — not
-- divided, not split, copied whole. Look at one customer:
SELECT c.firstName, c.lastName, c.moneySpent,
       count(*)          AS rows_after_join,
       sum(c.moneySpent) AS summed_after_join
FROM customers c
JOIN orders o ON o.customerID = c.customerID
WHERE c.customerID = 8
GROUP BY c.customerID, c.firstName, c.lastName, c.moneySpent;
--  firstname | lastname  | moneyspent | rows_after_join | summed_after_join
-- -----------+-----------+------------+-----------------+-------------------
--  Aram      | Vardanyan |   14625.38 |              40 |         585015.20
-- Compare moneySpent with summed_after_join: the same value, added
-- once for every order he placed.


-- ---- 4. The proof: count before you sum ----
SELECT count(*)                     AS rows,
       count(DISTINCT c.customerID) AS customers
FROM customers c
JOIN orders o ON o.customerID = c.customerID;
--  rows | customers
-- ------+-----------
--   600 |        28
-- Compare the two counts: how many rows are being summed, and how
-- many real customers are behind them.


-- ---- 5. The fix, in general ----
-- (a) Don't join at all if you already have the summary value:
SELECT sum(moneySpent) FROM customers;
--     sum
-- -----------
--  157078.41

-- (b) Or aggregate the fine-grain table FIRST, then join the result
--     back — one row per customer, so nothing can be copied:
SELECT sum(per_customer.spent) AS total_customer_spend
FROM (SELECT customerID, sum(orderTotal) AS spent
      FROM orders
      WHERE status = 'completed'
      GROUP BY customerID) AS per_customer
JOIN customers c ON c.customerID = per_customer.customerID;
--  total_customer_spend
-- ----------------------
--             157078.41
-- (A query inside a query: next lecture's topic.)


-- ---- The question to ask every time you aggregate after a join ----
-- "Is the thing I'm summing at the same grain as the rows I'm joining
--  through? If not, am I about to sum the same value multiple times?"



-- ============================================================
-- Lecture 4 — Joins, step 12: ON with non-equality conditions
-- Notes: Part 4.11
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- ON isn't limited to key = key. It accepts any true/false condition —
-- that's just "every pair, keep the ones that pass" again.
-- ============================================================


-- ---- 1. A small table typed into the query with VALUES ----
SELECT *
FROM (VALUES ('1. under 50',  0,    50),
             ('2. 50 - 299',  50,   300),
             ('3. 300 - 999', 300,  1000),
             ('4. 1000+',     1000, 100000)) AS b(band, low, high);
--      band     | low  |  high
-- --------------+------+--------
--  1. under 50  |    0 |     50
--  2. 50 - 299  |   50 |    300
--  3. 300 - 999 |  300 |   1000
--  4. 1000+     | 1000 | 100000


-- ---- 2. Join each order to the band its total falls in ----
SELECT b.band, count(*) AS orders, sum(o.orderTotal) AS revenue
FROM orders o
JOIN (VALUES ('1. under 50',  0,    50),
             ('2. 50 - 299',  50,   300),
             ('3. 300 - 999', 300,  1000),
             ('4. 1000+',     1000, 100000)) AS b(band, low, high)
  ON o.orderTotal >= b.low AND o.orderTotal < b.high
WHERE o.status = 'completed'
GROUP BY b.band
ORDER BY b.band;
--      band     | orders | revenue
-- --------------+--------+----------
--  1. under 50  |    121 |  3193.18
--  2. 50 - 299  |    251 | 35595.33
--  3. 300 - 999 |    120 | 66244.24
--  4. 1000+     |     37 | 52045.66
-- Add up the orders column: it equals the number of completed orders.
-- Each order lands in exactly one band, because the bands don't
-- overlap (>= low, < high).
-- Bucketing done natively in SQL, without a CASE per row. Tax
-- brackets and commission tiers are joins like this.



-- ============================================================
-- Lecture 4 — Joins, step 15: GROUP BY column order doesn't matter
-- Notes: Part 4.14 — clearing up a common misconception
-- Run after steps/00-setup.sql. Read-only: safe to re-run.
--
-- A group is defined by the COMBINATION of values in the listed
-- columns. The order you list them in changes nothing.
-- ============================================================


-- ---- 1. Revenue per city and category, grouped city first ----
SELECT c.city, p.category, sum(i.lineTotal) AS revenue
FROM orders o
JOIN customers   c ON c.customerID = o.customerID
JOIN order_items i ON i.orderID    = o.orderID
JOIN products    p ON p.productID  = i.productID
GROUP BY c.city, p.category
ORDER BY c.city, p.category;
--    city   |  category   | revenue
-- ----------+-------------+----------
-- ... 45 rows


-- ---- 2. Prove it: subtract the category-first version ----
SELECT c.city, p.category, sum(i.lineTotal) AS revenue
FROM orders o
JOIN customers   c ON c.customerID = o.customerID
JOIN order_items i ON i.orderID    = o.orderID
JOIN products    p ON p.productID  = i.productID
GROUP BY c.city, p.category
EXCEPT
SELECT c.city, p.category, sum(i.lineTotal) AS revenue
FROM orders o
JOIN customers   c ON c.customerID = o.customerID
JOIN order_items i ON i.orderID    = o.orderID
JOIN products    p ON p.productID  = i.productID
GROUP BY p.category, c.city;
--  city | category | revenue
-- ------+----------+---------
-- An empty result means: the same groups, the same totals.
-- (The same EXCEPT trick as step 14 — a check you can reuse anywhere.)


-- ---- Where to look instead ----
-- The order of the OUTPUT rows is decided by ORDER BY, never by
-- GROUP BY. And if a total looks wrong, GROUP BY column order is not
-- the place to look — check for a fan-out first (step 11).



-- ============================================================
-- Lecture 4 — Part 4: build a star (one fact row per order line)
-- Creates the star schema (safe to re-run).
-- ============================================================

DROP TABLE IF EXISTS fact_sales, dim_date, dim_customer, dim_product, dim_employee;
-- DROP TABLE

-- ---- Dimensions: the context ----
CREATE TABLE dim_date AS
SELECT d::date                        AS dateKey,
       EXTRACT(quarter FROM d)::int   AS quarter,
       EXTRACT(month FROM d)::int     AS month,
       to_char(d, 'Mon')              AS monthName,
       EXTRACT(isodow FROM d)::int    AS dayOfWeek,
       to_char(d, 'Dy')               AS dayName
FROM generate_series(DATE '2024-01-01', DATE '2024-12-31', INTERVAL '1 day') AS d;
-- SELECT 366

ALTER TABLE dim_date ADD PRIMARY KEY (dateKey);
-- ALTER TABLE

CREATE TABLE dim_customer AS
SELECT customerID                         AS customerKey,
       firstName || ' ' || lastName       AS customerName,
       city,
       EXTRACT(year FROM signupDate)::int AS signupYear
FROM customers;
-- SELECT 30

CREATE TABLE dim_product AS
SELECT productID AS productKey, productName, brand, category
FROM products;
-- SELECT 37

ALTER TABLE dim_customer ADD PRIMARY KEY (customerKey);
-- ALTER TABLE
ALTER TABLE dim_product  ADD PRIMARY KEY (productKey);
-- ALTER TABLE

CREATE TABLE dim_employee AS
SELECT e.employeeID                                          AS employeeKey,
       e.firstName || ' ' || e.lastName                      AS employeeName,
       e.branch,
       coalesce(m.firstName || ' ' || m.lastName, '(none)')  AS managerName
FROM employees e
LEFT JOIN employees m ON m.employeeID = e.managerID;
-- SELECT 8

-- The unknown member: online orders get employee key 0, never NULL.
INSERT INTO dim_employee VALUES (0, '(online)', 'Online', '(none)');
-- INSERT 0 1

ALTER TABLE dim_employee ADD PRIMARY KEY (employeeKey);
-- ALTER TABLE

-- ---- The fact table. Grain: one row per order LINE ----
-- One row per product in an order, so revenue can be split by product
-- and category. Order-level columns (date, customer, employee, status)
-- are copied onto each of the order's lines.
CREATE TABLE fact_sales AS
SELECT o.orderID,
       i.productID                 AS productKey,
       o.orderDate                 AS dateKey,
       o.customerID                AS customerKey,
       coalesce(o.employeeID, 0)   AS employeeKey,
       o.channel,
       o.status,
       i.quantity,
       i.lineTotal                 AS revenue,
       i.quantity * p.cost         AS cost
FROM orders o
JOIN order_items i ON i.orderID   = o.orderID
JOIN products    p ON p.productID = i.productID;
-- SELECT 965

ALTER TABLE fact_sales
    ADD PRIMARY KEY (orderID, productKey),
    ADD FOREIGN KEY (dateKey)     REFERENCES dim_date,
    ADD FOREIGN KEY (customerKey) REFERENCES dim_customer,
    ADD FOREIGN KEY (productKey)  REFERENCES dim_product,
    ADD FOREIGN KEY (employeeKey) REFERENCES dim_employee;
-- ALTER TABLE

-- ---- Check the build: same money as the source tables ----
SELECT count(*) AS fact_rows,
       count(DISTINCT orderID) AS orders,
       sum(revenue) FILTER (WHERE status = 'completed') AS completed_revenue
FROM fact_sales;
--  fact_rows | orders | completed_revenue
-- -----------+--------+-------------------
--        965 |    600 |         157078.41

-- ---- Completed revenue per branch, per quarter: plain inner joins ----
SELECT e.branch,
       sum(f.revenue) FILTER (WHERE d.quarter = 1) AS q1,
       sum(f.revenue) FILTER (WHERE d.quarter = 2) AS q2,
       sum(f.revenue) FILTER (WHERE d.quarter = 3) AS q3,
       sum(f.revenue) FILTER (WHERE d.quarter = 4) AS q4,
       sum(f.revenue)                              AS total
FROM fact_sales f
JOIN dim_date     d ON d.dateKey     = f.dateKey
JOIN dim_employee e ON e.employeeKey = f.employeeKey
WHERE f.status = 'completed'
GROUP BY e.branch
ORDER BY total DESC;
--      branch     |   q1    |    q2    |    q3    |    q4    |  total
-- ----------------+---------+----------+----------+----------+----------
--  Online         | 5414.54 | 16490.92 | 16278.88 | 18671.59 | 56855.93
--  Yerevan Center | 9307.89 | 13527.83 | 14588.32 | 14334.11 | 51758.15
--  Yerevan Mall   | 5302.56 |  7334.19 |  9004.66 | 16366.75 | 38008.16
--  Gyumri         | 3467.63 |  1870.25 |   277.15 |  4841.14 | 10456.17

-- ---- Margin by category, Saturdays vs the whole year (line grain) ----
SELECT p.category,
       sum(f.revenue - f.cost) FILTER (WHERE d.dayName = 'Sat') AS sat_margin,
       sum(f.revenue - f.cost)                                  AS year_margin
FROM fact_sales f
JOIN dim_date    d ON d.dateKey    = f.dateKey
JOIN dim_product p ON p.productKey = f.productKey
WHERE f.status = 'completed'
GROUP BY p.category
ORDER BY year_margin DESC
LIMIT 5;
--   category   | sat_margin | year_margin
-- -------------+------------+-------------
--  Laptops     |    1315.00 |     9472.00
--  Audio       |     479.65 |     5118.90
--  Phones      |     565.00 |     4921.90
--  Accessories |     692.75 |     4132.96
--  Monitors    |     757.00 |     2768.20



-- ============================================================
-- Lecture 4 — Part 5: verification drill
-- Read-only.
-- ============================================================

-- Each query runs without error and returns a believable answer.
-- Each one is wrong. Name the problem before reading the answers.

-- Q1. "Total completed revenue for 2024, with who sold it."
SELECT sum(o.orderTotal) AS revenue
FROM orders o
JOIN employees e ON e.employeeID = o.employeeID
WHERE o.status = 'completed';
--   revenue
-- -----------
--  100222.48

-- Q2. "Customers with the fewest orders: who needs a reminder email?"
SELECT c.firstName, c.lastName, count(*) AS orders
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
GROUP BY c.customerID, c.firstName, c.lastName
HAVING count(*) <= 5
ORDER BY orders, c.lastName;
--  firstname |  lastname  | orders
-- -----------+------------+--------
--  Levon     | Arakelyan  |      1
--  Astghik   | Danielyan  |      1
--  Diana     | Aleksanyan |      4
--  Lusine    | Avetisyan  |      5

-- Q3. "Completed revenue for every product category, including those with none."
SELECT p.category, coalesce(sum(i.lineTotal), 0) AS revenue
FROM products p
LEFT JOIN order_items i ON i.productID = p.productID
LEFT JOIN orders      o ON o.orderID   = i.orderID
WHERE o.status = 'completed'
GROUP BY p.category;
--   category   | revenue
-- -------------+----------
-- ... 12 rows

-- Q4. "Average lifetime spend of the customers who bought in December."
SELECT round(avg(c.moneySpent), 2) AS avg_spend
FROM customers c
JOIN orders o ON o.customerID = c.customerID
WHERE o.orderDate BETWEEN '2024-12-01' AND '2024-12-31';
--  avg_spend
-- -----------
--    7339.20

-- ---- Answers ----
-- Q1: the inner join dropped the 181 online orders. Without the join:
SELECT sum(orderTotal) AS revenue FROM orders WHERE status = 'completed';
--   revenue
-- -----------
--  157078.41

-- Q2: count(*) counted the empty match. Count the right table's key:
SELECT c.firstName, c.lastName, count(o.orderID) AS orders
FROM customers c
LEFT JOIN orders o ON o.customerID = c.customerID
GROUP BY c.customerID, c.firstName, c.lastName
HAVING count(o.orderID) <= 5
ORDER BY orders, c.lastName;
--  firstname |  lastname  | orders
-- -----------+------------+--------
--  Levon     | Arakelyan  |      0
--  Astghik   | Danielyan  |      0
--  Diana     | Aleksanyan |      4
--  Lusine    | Avetisyan  |      5

-- Q3: WHERE undid the LEFT JOIN. Decide what counts as a match first:
SELECT p.category, coalesce(sum(i.lineTotal), 0) AS revenue
FROM products p
LEFT JOIN (order_items i
           JOIN orders o ON o.orderID = i.orderID
                        AND o.status  = 'completed')
       ON i.productID = p.productID
GROUP BY p.category;
--   category   | revenue
-- -------------+----------
-- ... 13 rows

-- Q4: fan-out -- one row per December ORDER, so big buyers count
-- several times. Pick each customer once:
SELECT round(avg(moneySpent), 2) AS avg_spend, count(*) AS customers
FROM customers
WHERE customerID IN (SELECT customerID FROM orders
                     WHERE orderDate BETWEEN '2024-12-01' AND '2024-12-31');
--  avg_spend | customers
-- -----------+-----------
--    5864.44 |        26
